/**
 * Curated root graph surface.
 *
 * Internal callers should prefer the owning package (`@io/graph-kernel`,
 * `@io/graph-authority`, `@io/graph-bootstrap`, and friends) over this umbrella
 * barrel. Module-definition authoring now lives on `@io/graph-module`; this
 * surface stays focused on low-level kernel aliases plus root-owned helpers
 * such as SVG sanitization.
 */
export {
  applyGraphIdMap as applyIdMap,
  cloneGraphStoreSnapshot as cloneStoreSnapshot,
  createGraphId,
  createGraphIdMap as createIdMap,
  createGraphStore as createStore,
  createFallbackPolicyDescriptor,
  edgeId,
  extractGraphSchemaKeys as extractSchemaKeys,
  fieldPolicyDescriptor,
  fieldPolicyFallbackContractVersion,
  fieldSecretMetadataVisibility,
  fieldTreeId,
  fieldTreeKey,
  fieldVisibility,
  fieldWritePolicy,
  findDuplicateGraphIds as findDuplicateIds,
  graphFieldVisibilities,
  graphFieldWritePolicies,
  isEntityType,
  isEnumType,
  isFieldsOutput,
  isGraphFieldVisibility,
  isGraphFieldWritePolicy,
  isScalarType,
  isSecretBackedField,
  rangeOf,
  resolveFieldPolicyDescriptor,
  typeId,
  type AnyEnumTypeOutput,
  type AnyTypeOutput,
  type Cardinality,
  type DefinitionIconRef,
  type EdgeInput,
  type EdgeOutput,
  type EncodedValue,
  type EntityTypeInput,
  type EntityTypeOutput,
  type EnumOptionInput,
  type EnumTypeInput,
  type EnumTypeOutput,
  type FieldsInput,
  type FieldsOutput,
  type GraphFact,
  type GraphFieldAuthority,
  type GraphFieldVisibility,
  type GraphFieldWritePolicy,
  type GraphIconSeedRecord,
  type GraphId,
  type GraphIdMap,
  type GraphSecretFieldAuthority,
  type GraphStore,
  type GraphStoreSnapshot,
  type PredicatePolicyDefinition,
  type PredicatePolicyDescriptor,
  type PredicateSlotListener,
  type RangeRef,
  type ResolvedGraphNamespace,
  type ScalarTypeInput,
  type ScalarTypeOutput,
  type ValidationIssueInput,
} from "@io/graph-kernel";

export { sanitizeSvgMarkup, type SvgSanitizationResult } from "./icon.js";
