/**
 * Public entrypoint for the graph client package.
 *
 * This surface owns local typed graph access, client-side validation, synced
 * client composition, and client transport helpers. Authority storage,
 * projection routing, and React bindings stay outside this package.
 */
export { createEntityWithId, createGraphClient, validateGraphStore } from "./graph.js";
export {
  collectScalarCodecs,
  collectTypeIndex,
  fieldGroupMeta,
  fieldGroupFieldTree,
  fieldGroupId,
  fieldGroupKey,
  fieldGroupPath,
  fieldGroupSubjectId,
  formatValidationPath,
  isFieldGroupRef,
  GraphValidationError,
  readPredicateValue,
  type CreateInputOfType,
  type EntityOfType,
  type EntityRef,
  type FieldGroupRef,
  type GraphDeleteValidationResult,
  type GraphMutationValidationResult,
  type GraphValidationIssue,
  type GraphValidationResult,
  type GraphValidationSource,
  type GraphClient,
  type PredicateCollectionKind,
  type PredicateCollectionSemantics,
  type PredicateItemOf,
  type PredicateRangeEntityRefOf,
  type PredicateRangeEntityTypeOf,
  type PredicateRangeTypeOf,
  type PredicateRef,
  type PredicateSetValueOf,
  type PredicateValueOf,
  type QueryFieldResult,
  type TypeByKey,
  type TypeQueryResponse,
  type TypeQueryResult,
  type TypeQuerySelection,
  type TypeQuerySpec,
  type TypeQueryWhere,
} from "./core.js";
export {
  createSyncedGraphClient,
  GraphSyncWriteError,
  type GraphClientSyncState,
  type GraphClientSyncStateListener,
  type GraphClientSyncStatus,
  type GraphClientSyncController,
  type GraphWriteSink,
  type SyncedGraphClient,
} from "./sync.js";
export {
  createHttpGraphClient,
  createHttpGraphTxIdFactory,
  defaultHttpGraphUrl,
  defaultHttpSerializedQueryPath,
  HttpSerializedQueryClientError,
  requestSerializedQuery,
  type FetchImpl,
  type HttpGraphClientOptions,
  type HttpSerializedQueryClientOptions,
} from "./http.js";
export {
  applyHttpSyncRequest,
  readHttpSyncRequest,
  type HttpSyncRequest,
} from "./http-sync-request.js";
export {
  queryFilterOperatorValues,
  queryOrderDirectionValues,
  queryParameterTypeValues,
  serializedQueryVersion,
  serializedScopeKindValues,
  normalizeSerializedQueryRequest,
  validateSerializedQueryRequest,
  validateSerializedQueryResponse,
  SerializedQueryValidationError,
  type CollectionReadQuery,
  type EntityReadQuery,
  type NeighborhoodReadQuery,
  type NormalizedCollectionReadQuery,
  type NormalizedEntityReadQuery,
  type NormalizedNeighborhoodReadQuery,
  type NormalizedQueryFilter,
  type NormalizedQueryMetadata,
  type NormalizedQueryParameterBinding,
  type NormalizedQueryRequest,
  type NormalizedReadQuery,
  type NormalizedScopeDefinition,
  type NormalizedScopeReadQuery,
  type QueryFilter,
  type QueryFilterOperator,
  type QueryIdentityExecutionContext,
  type QueryLiteral,
  type QueryOrderClause,
  type QueryOrderDirection,
  type QueryParameterDefinition,
  type QueryParameterType,
  type QueryResultItem,
  type QueryResultPage,
  type QueryValue,
  type QueryWindow,
  type ReadQuery,
  type ScopeReadQuery,
  type SerializedQueryErrorResponse,
  type SerializedQueryNormalizationOptions,
  type SerializedQueryRequest,
  type SerializedQueryResponse,
  type SerializedQuerySuccessResponse,
  type SerializedQueryValidationOptions,
  type SerializedScopeDefinition,
  type SerializedScopeKind,
} from "./serialized-query.js";
