export * from "./type.js";
export * from "./command.js";
export * from "./projection.js";
export * from "./query.js";

import {
  agentSession,
  agentSessionEvent,
  agentSessionEventPhase,
  agentSessionEventType,
  agentSessionKind,
  agentSessionRawLineEncoding,
  agentSessionRuntimeState,
  agentSessionStatusCode,
  agentSessionStatusFormat,
  agentSessionStream,
  agentSessionSubjectKind,
  contextBundle,
  contextBundleEntry,
  contextBundleEntrySource,
  repositoryBranch,
  repositoryCommit,
  repositoryCommitLeaseState,
  repositoryCommitState,
  artifact,
  artifactKind,
  branch,
  branchState,
  commit,
  commitState,
  decision,
  decisionKind,
  project,
  repository,
} from "./type.js";

export const workflowSchema = {
  project,
  repository,
  branchState,
  branch,
  commitState,
  commit,
  repositoryCommitState,
  repositoryCommitLeaseState,
  repositoryBranch,
  repositoryCommit,
  agentSessionSubjectKind,
  agentSessionKind,
  agentSessionRuntimeState,
  agentSession,
  agentSessionEventType,
  agentSessionEventPhase,
  agentSessionStatusCode,
  agentSessionStatusFormat,
  agentSessionStream,
  agentSessionRawLineEncoding,
  agentSessionEvent,
  artifactKind,
  artifact,
  decisionKind,
  decision,
  contextBundle,
  contextBundleEntrySource,
  contextBundleEntry,
} as const;
