/**
 * Public entrypoint for the graph kernel package.
 *
 * This surface intentionally stops at opaque ids, append-oriented fact
 * storage, schema authoring, stable key-to-id resolution, and authoritative
 * write envelope types. Bootstrap, typed client helpers, sync sessions, and
 * authority storage live in higher layers.
 */
export { createGraphId, type GraphId } from "./id.js";

export {
  cloneStoreSnapshot,
  createStore,
  type GraphFact,
  type GraphStore,
  type GraphStoreSnapshot,
  type EncodedValue,
  type PredicateSlotListener,
} from "./store.js";

export {
  defineEnum,
  defineScalar,
  defineType,
  edgeId,
  fieldPolicyDescriptor,
  fieldSecretMetadataVisibility,
  fieldTreeId,
  fieldTreeKey,
  fieldVisibility,
  fieldWritePolicy,
  graphFieldVisibilities,
  graphFieldWritePolicies,
  isEntityType,
  isEnumType,
  isFieldsOutput,
  isGraphFieldVisibility,
  isGraphFieldWritePolicy,
  isScalarType,
  isSecretBackedField,
  rangeOf,
  typeId,
  type AnyEnumTypeOutput,
  type AnyTypeOutput,
  type Cardinality,
  type EdgeInput,
  type EdgeOutput,
  type EntityTypeInput,
  type EntityTypeOutput,
  type EnumOptionInput,
  type EnumTypeInput,
  type EnumTypeOutput,
  type FieldsInput,
  type FieldsOutput,
  type GraphFieldAuthority,
  type GraphFieldVisibility,
  type GraphFieldWritePolicy,
  type GraphSecretFieldAuthority,
  type PolicyAudience,
  type PolicyCapabilityKey,
  type PolicyMutationMode,
  type PredicateHookContext,
  type PredicateLifecycleEvent,
  type PredicatePolicyDefinition,
  type PredicatePolicyDescriptor,
  type PredicateValidationContext,
  type PredicateValidator,
  type PredicateValueHook,
  type RangeRef,
  type ResolvedAnyEnumTypeOutput,
  type ResolvedAnyTypeOutput,
  type ResolvedEdgeOutput,
  type ResolvedEntityTypeOutput,
  type ResolvedEnumTypeOutput,
  type ResolvedScalarTypeOutput,
  type ResolvedTypeOutput,
  type ScalarTypeInput,
  type ScalarTypeOutput,
  type ScalarValidationContext,
  type ScalarValueValidator,
  type TypeOutput,
  type ValidationEvent,
  type ValidationIssueInput,
  type ValidationPhase,
} from "./schema.js";

export {
  applyIdMap,
  createIdMap,
  extractSchemaKeys,
  findDuplicateIds,
  type GraphIdMap,
  type ResolvedNamespace,
} from "./identity.js";

export {
  authoritativeWriteScopes,
  canonicalizeGraphWriteTransaction,
  cloneAuthoritativeGraphRetainedHistoryPolicy,
  cloneAuthoritativeGraphWriteResult,
  cloneGraphWriteOperation,
  cloneGraphWriteTransaction,
  createGraphWriteOperationsFromSnapshots,
  createGraphWriteTransactionFromSnapshots,
  isAuthoritativeGraphRetainedHistoryPolicy,
  isAuthoritativeWriteScope,
  sameAuthoritativeGraphRetainedHistoryPolicy,
  sameGraphWriteTransaction,
  unboundedAuthoritativeGraphRetainedHistoryPolicy,
  type AuthoritativeGraphChangesAfterResult,
  type AuthoritativeGraphCursor,
  type AuthoritativeGraphRetainedHistoryPolicy,
  type AuthoritativeGraphWriteHistory,
  type AuthoritativeGraphWriteResult,
  type AuthoritativeWriteScope,
  type GraphWriteAssertOperation,
  type GraphWriteOperation,
  type GraphWriteRetractOperation,
  type GraphWriteTransaction,
} from "./tx.js";
