/**
 * Public entrypoint for the graph kernel package.
 *
 * This surface intentionally stops at opaque ids, append-oriented fact
 * storage, schema authoring, stable key-to-id resolution, and authoritative
 * write envelope types. The root exports use explicit graph-prefixed factory
 * names so adjacent extracted packages can depend on one self-describing
 * contract. Bootstrap, typed client helpers, sync sessions, and authority
 * storage live in higher layers.
 */
export { createGraphId, type GraphId } from "./id.js";
export { fieldsMeta as fieldTreeMeta } from "./field-tree-meta.js";

export {
  cloneStoreSnapshot as cloneGraphStoreSnapshot,
  createStore as createGraphStore,
  type GraphFact,
  type GraphStore,
  type GraphStoreSnapshot,
  type EncodedValue,
  type PredicateSlotListener,
} from "./store.js";

export {
  createFallbackPolicyDescriptor,
  defineEnum,
  defineScalar,
  defineType,
  edgeId,
  fieldPolicyFallbackContractVersion,
  fieldPolicyDescriptor,
  fieldSecretMetadataVisibility,
  fieldTreeId,
  fieldTreeKey,
  fieldVisibility,
  fieldWritePolicy,
  graphFieldVisibilities,
  graphFieldWritePolicies,
  isEntityType,
  isEnumType,
  isFieldsOutput,
  isGraphFieldVisibility,
  isGraphFieldWritePolicy,
  isScalarType,
  isSecretBackedField,
  readDefinitionIconId,
  rangeOf,
  resolveFieldPolicyDescriptor,
  typeId,
  type AnyEnumTypeOutput,
  type AnyTypeOutput,
  type Cardinality,
  type DefinitionIconRef,
  type EdgeInput,
  type EdgeOutput,
  type EntityTypeInput,
  type EntityTypeOutput,
  type EnumOptionInput,
  type EnumTypeInput,
  type EnumTypeOutput,
  type FieldsInput,
  type FieldsOutput,
  type GraphFieldAuthority,
  type GraphFieldVisibility,
  type GraphFieldWritePolicy,
  type GraphIconSeedRecord,
  type GraphSecretFieldAuthority,
  type PolicyAudience,
  type PolicyCapabilityKey,
  type PolicyMutationMode,
  type PredicateHookContext,
  type PredicateLifecycleEvent,
  type PredicatePolicyDefinition,
  type PredicatePolicyDescriptor,
  type PredicateValidationContext,
  type PredicateValidator,
  type PredicateValueHook,
  type RangeRef,
  type ResolvedAnyEnumTypeOutput,
  type ResolvedAnyTypeOutput,
  type ResolvedEdgeOutput,
  type ResolvedEntityTypeOutput,
  type ResolvedEnumTypeOutput,
  type ResolvedScalarTypeOutput,
  type ResolvedTypeOutput,
  type ScalarTypeInput,
  type ScalarTypeOutput,
  type ScalarValidationContext,
  type ScalarValueValidator,
  type TypeOutput,
  type ValidationEvent,
  type ValidationIssueInput,
  type ValidationPhase,
} from "./schema.js";

export {
  applyIdMap as applyGraphIdMap,
  createIdMap as createGraphIdMap,
  extractSchemaKeys as extractGraphSchemaKeys,
  findDuplicateIds as findDuplicateGraphIds,
  type GraphIdMap,
  type ResolvedNamespace as ResolvedGraphNamespace,
} from "./identity.js";

export {
  canonicalizeGraphWriteTransaction,
  cloneAuthoritativeGraphRetainedHistoryPolicy,
  cloneAuthoritativeGraphWriteResult,
  cloneGraphWriteOperation,
  cloneGraphWriteTransaction,
  createGraphWriteOperationsFromSnapshots,
  createGraphWriteTransactionFromSnapshots,
  graphWriteScopes,
  isAuthoritativeGraphRetainedHistoryPolicy,
  isGraphWriteScope,
  sameAuthoritativeGraphRetainedHistoryPolicy,
  sameGraphWriteTransaction,
  unboundedAuthoritativeGraphRetainedHistoryPolicy,
  type AuthoritativeGraphChangesAfterResult,
  type AuthoritativeGraphCursor,
  type AuthoritativeGraphRetainedHistoryPolicy,
  type AuthoritativeGraphWriteHistory,
  type AuthoritativeGraphWriteResult,
  type GraphWriteScope,
  type GraphWriteAssertOperation,
  type GraphWriteOperation,
  type GraphWriteRetractOperation,
  type GraphWriteTransaction,
} from "./tx.js";
